# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/todo_django

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys: globe-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache:
          key: globe-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      - run:
          name: run tests
          command: |
            pipenv run python manage.py test

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports