# Generated by Django 2.1.7 on 2019-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190222_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('T', 'TODO'), ('S', 'STARTED'), ('W', 'WAITING'), ('D', 'DONE'), ('C', 'CANCELLED')], default='T', max_length=1),
        ),
    ]
